# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dev" do |dev|
    dev.vm.box = "ubuntu/focal64"
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.0.1"
    dev.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "dev"
    end
  end

  config.vm.define "prod" do |prod|
    prod.vm.box = "ubuntu/focal64"
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.0.2"
    prod.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "prod"
    end
  end
end
